Repository CommunityPro/portfolio-html, pull requests merged in 2022-01, with the labels that each got.

#23 Update Template
  template/Portfolio Template Dark Mode.png
  template/Portfolio Template Light Mode.png
  template/Portfolio Template.zip
Labels: bug

#28 Rename folders
  design/Portfolio Template Dark Mode.png
  design/Portfolio Template Light Mode.png
  template/assets/logo.png
  template/assets/profile-image.png
  template/css/style.css
  template/index.html
  template/js/script.js
Labels: bug, status: completed

#30 Add code requirement in comments
  template/css/custom.css
  template/css/style.css
Labels: enhancement

#36 Add style guide
  template/css/custom.css
  template/css/style.css
  template/css/utilities.css
Labels: enhancement, status: completed

#38 Style navbar
  template/assets/logo.png
  template/css/style.css
  template/css/utilities.css
  template/index.html
Labels: enhancement

#47 Add Template Steps
  README.md
Labels: documentation, status: work in progress

#54 Add dark toggle script
  template/assets/sun.svg
  template/css/utilities.css
  template/js/script.js
Labels: status: completed

#67 Generate Meta Tags
  template/index.html
Labels: status: work in progress

#69 Add Font Awesome Link
  template/index.html
Labels: enhancement

#74 Add project section
  template/assets/github-icon.svg
  template/assets/link-icon.svg
  template/css/style.css
  template/css/utilities.css
  template/index.html
Labels: enhancement, status: completed

#83 add images to the project folder
  docs/assets/project/project-five.png
  docs/assets/project/project-four.png
  docs/assets/project/project-one.png
  docs/assets/project/project-six.png
  docs/assets/project/project-three.png
  docs/assets/project/project-two.png
Labels: enhancement

#84 Add project cards animation
  docs/css/style.css
  docs/css/utilities.css
  docs/index.html
Labels: enhancement, status: completed

#85 Add link hover
  docs/css/utilities.css
Labels: enhancement, good first issue

#103 Style footer
  docs/assets/facebook-icon.svg
  docs/assets/github-icon.svg
  docs/assets/hashnode-icon.svg
  docs/assets/link-icon.svg
  docs/assets/linkedin-icon.svg
  docs/assets/twitter-icon.svg
  docs/css/style.css
  docs/index.html
Labels: enhancement

#105 Make page responsive
  docs/css/style.css
  docs/css/utilities.css
  docs/index.html
Labels: enhancement, status: completed

#107 Fix toogle issue
  docs/assets/moon.svg
  docs/assets/sun.svg
  docs/css/utilities.css
  docs/index.html
Labels: enhancement
